application:
  check-root-user: true

twig:
  baseDirs:

plugin:
  folders:
    - /usr/local/share/imi-conrun/modules

helpers:
  database: IMI\Util\Console\Helper\DatabaseHelper
  dialog: Composer\Command\Helper\DialogHelper
  parameter: IMI\Util\Console\Helper\ParameterHelper
  table: IMI\Util\Console\Helper\TableHelper

script:
  folders:
    - /usr/local/share/imi-conrun/scripts

init:
  code: admin
  type: store
  options: []

detect:
  subFolders:
    - web
    - www
    - htdocs
    - public
    - pub
    - webroot
    - web-root
    - wwwroot

event:
  subscriber:
    - IMI\Contao\EventSubscriber
    - IMI\Contao\Command\ComposerWrapper\EventSubscriber

commands:
  customCommands:
    - IMI\Contao\Command\Database\ConsoleCommand
    - IMI\Contao\Command\Database\CreateCommand
    - IMI\Contao\Command\Database\DropCommand
    - IMI\Contao\Command\Database\DumpCommand
    - IMI\Contao\Command\Database\ImportCommand
    - IMI\Contao\Command\Database\InfoCommand
    - IMI\Contao\Command\Database\QueryCommand
    - IMI\Contao\Command\Database\VariablesCommand
    - IMI\Contao\Command\Database\StatusCommand
    - IMI\Contao\Command\Database\Maintain\CheckTablesCommand
    - IMI\Contao\Command\Admin\User\CreateUserCommand
    - IMI\Contao\Command\Admin\User\ListCommand
    - IMI\Contao\Command\Admin\User\DeleteUserCommand
    - IMI\Contao\Command\Admin\User\ChangePasswordCommand
    - IMI\Contao\Command\Developer\Log\FollowCommand
    - IMI\Contao\Command\ScriptCommand
    - IMI\Contao\Command\SelfUpdateCommand
    - IMI\Contao\Command\System\InfoCommand
    - IMI\Contao\Command\System\Setup\RunCommand
    - IMI\Contao\Command\System\Setup\PreviewCommand
    - IMI\Contao\Command\Cache\FlushCommand
    - IMI\Contao\Command\Cache\ListCommand

  disabled:
    - dummy

  aliases: []

  IMI\Contao\Command\Installer\InstallCommand:
    contao-packages:
      - name: contao-ce-1.9.0.1
        version: 1.9.0.1
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.9.0.1/contao-1.9.0.1.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.9.0.0

      - name: contao-ce-1.8.1.0
        version: 1.8.1.0
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.8.1.0/contao-1.8.1.0.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-ce-1.8.0.0
        version: 1.8.0.0
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.8.0.0/contao-1.8.0.0.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-ce-1.7.0.2
        version: 1.7.0.2
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.7.0.2/contao-1.7.0.2.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-ce-1.6.2.0
        version: 1.6.2.0
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.6.2.0/contao-1.6.2.0.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-mirror-1.7.0.2
        version: 1.7.0.2
        dist:
          url: https://github.com/LokeyCoding/contao-mirror/archive/1.7.0.2.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-mirror-1.6.2.0
        version: 1.6.2.0
        dist:
          url: https://github.com/LokeyCoding/contao-mirror/archive/1.6.2.0.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-mirror-1.5.1.0
        version: 1.5.1.0
        source:
          url: git://github.com/LokeyCoding/contao-mirror.git
          type: git
          reference: contao-1.5
        extra:
          sample-data: sample-data-1.1.2

      - name: contao-mirror-1.4.2.0
        version: 1.4.2.0
        source:
          url: git://github.com/LokeyCoding/contao-mirror.git
          type: git
          reference: contao-1.4
        extra:
          sample-data: sample-data-1.1.2

      - name: mageplus-master
        version: dev-master
        source:
          url: https://github.com/mageplus/mageplus.git
          type: git
          reference: master
        extra:
          sample-data: sample-data-1.6.1.0

      - name: contao-ce-2.0.0.0-dev (experimental)
        version: 2.0.0.0-dev
        source:
          url: https://github.com/contao/contao2.git
          type: git
          reference: master

    demo-data-packages:
      - name: sample-data-1.9.0.0
        version: 1.9.0.0
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.9.0.0/contao-sample-data-1.9.0.0.tar.gz
          type: tar
      - name: sample-data-1.6.1.0
        version: 1.6.1.0
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.6.1.0/contao-sample-data-1.6.1.0.tar.gz
          type: tar
      - name: sample-data-1.1.2
        version: 1.1.2
        dist:
          url: http://www.contaocommerce.com/downloads/assets/1.1.2/contao-sample-data-1.1.2.tar.bz2
          type: tar

    installation:
      pre-check:
        php:
          extensions:
            - pdo_mysql
            - spl
            - dom
            - simplexml
            - mcrypt
            - hash
            - curl
            - iconv
            - ctype
            - gd

      defaults:
        currency: EUR
        locale: de_DE
        timezone: Europe/Berlin
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com
        encryption_key:

  IMI\Contao\Command\Database\DumpCommand:
    table-groups:
      - id: log
        description: Log tables
        tables: tl_log

      - id: versions
        description: Versioning
        tables: tl_undo tl_verion

      - id: sessions
        description: Database session tables
        tables: tl_session

      - id: stripped
        description: Standard definition for a stripped dump (logs and dataflow)
        tables: @stripped @log @sessions

      - id: newsletter
        description: Newsletter Recepients
        tables: tl_newsletter_recipients

      - id: customers
        description: Member data
        tables: tl_member_*

      - id: development
        description: Removes logs and customer data as well as search
        tables: @newsletter @customers @stripped @search

      - id: search
        description: Search related tables
        tables: "tl_search tl_search_index"


  IMI\Contao\Command\Customer\ListCommand:
    limit: 1000

  IMI\Contao\Command\System\CheckCommand:
    checks:
      settings:
        - IMI\Contao\Command\System\Check\Settings\SecureBaseUrlCheck
        - IMI\Contao\Command\System\Check\Settings\UnsecureBaseUrlCheck
        - IMI\Contao\Command\System\Check\Settings\SecureCookieDomainCheck
        - IMI\Contao\Command\System\Check\Settings\UnsecureCookieDomainCheck
      filesystem:
        - IMI\Contao\Command\System\Check\Filesystem\FoldersCheck
        - IMI\Contao\Command\System\Check\Filesystem\FilesCheck
      php:
        - IMI\Contao\Command\System\Check\PHP\ExtensionsCheck
        - IMI\Contao\Command\System\Check\PHP\BytecodeCacheExtensionsCheck
      security:
        - IMI\Contao\Command\System\Check\Security\LocalConfigAccessableCheck
      mysql:
        - IMI\Contao\Command\System\Check\MySQL\VersionCheck
        - IMI\Contao\Command\System\Check\MySQL\EnginesCheck

    filesystem:
      folders:
        media: "Used for images and other media files."
        var: "Used for caching, reports, etc."
        var/cache: "Used for caching"
        var/session: "Used as file based session save"

      files:
        app/etc/local.xml: "Contao local configuration."
        index.php.sample: "Used to generate staging websites in Contao enterprise edition"

    php:
      required-extensions:
        - simplexml
        - mcrypt
        - hash
        - gd
        - dom
        - iconv
        - curl
        - soap
        - pdo
        - pdo_mysql

      bytecode-cache-extensions:
        - apc
        - eaccelerator
        - xcache
        - Zend Optimizer
        - Zend OPcache

  IMI\Contao\Command\Media\DumpCommand:
    strip:
      folders:
        - catalog/product/cache
        - css
        - js
